### ISSUE TITLE
error in mean_prodigal_length.sh script?

### ISSUE THREAD

**Issue by Cat-Jane** [rrwick/Perfect-bacterial-genome-tutorial#1]
**Trying to run the mean_prodigal_length.sh, kept getting the following error message:**

$ ./mean_prodigal_length.sh 7_final_consensus.fasta

PRODIGAL v2.6.3 [February, 2016]
Univ of Tenn / Oak Ridge National Lab
Doug Hyatt, Loren Hauser, et al.

Error: can't open input file trycycler.fasta.

awk: cmd. line:1: fatal: division by zero attempted

**Looking at the script:**

if [[ -z "$1" ]] ; then echo "you must provide an assembly filename"; exit 1; fi
if [[ ! -f "$1" ]] ; then echo $1" does not exist"; exit 1; fi

prod=$(mktemp)

prodigal -a "$prod" -i trycycler.fasta > /dev/null
seqtk seq "$prod" | awk 'NR % 2 == 0' | awk '{sum += length($0); n++} END {print sum/n;}' > "$1".prod

rm "$prod"

**Was able to run by making the following modification:**

if [[ -z "$1" ]] ; then echo "you must provide an assembly filename"; exit 1; fi
if [[ ! -f "$1" ]] ; then echo $1" does not exist"; exit 1; fi

prod=$(mktemp)

prodigal -a "$prod" -i "$1" > /dev/null
seqtk seq "$prod" | awk 'NR % 2 == 0' | awk '{sum += length($0); n++} END {print sum/n;}' > "$1".prod

rm "$prod"

Sorry if this isn't in the right format for reporting an issue, I've never posted one of these before and I'm self-taught so don't know the conventions. Happy to be corrected. 

Thanks.

**Comment by rrwick** [comment]
Thank you! Sloppy mistake on my part 😳 This should be fixed now from pull request #2.
