### ISSUE TITLE
miniasm_and_minipolish.sh is missing

### ISSUE THREAD

**Issue by schlaepferp** [rrwick/Perfect-bacterial-genome-tutorial#10]
Dear Sir or Madam,

I noted that whenever installing from yml, I can't find miniasm_and_minipolish.sh I found it in one of the repositories, however, I suggest to add it here or note where it is. Just running your example commands from the easy Howto, does not work.

Best,
Pascal

**Comment by rrwick** [comment]
Thanks for pointing that out - you're right that the conda install doesn't include the `miniasm_and_minipolish.sh` script.

Here's how you could include it in your conda environment
```bash
wget https://raw.githubusercontent.com/rrwick/Minipolish/main/miniasm_and_minipolish.sh
chmod +x miniasm_and_minipolish.sh
mv miniasm_and_minipolish.sh ~/.conda/envs/assembly/bin  # change this path to match your conda environment
```

I've also added a note to the [Requirements page](https://github.com/rrwick/Perfect-bacterial-genome-tutorial/wiki/Requirements) which explains this.

Ryan
