### ISSUE TITLE
edlib error with compare_assemblies

### ISSUE THREAD

**Issue by rwilton1** [rrwick/Perfect-bacterial-genome-tutorial#11]
Hello,
I'd like to use your compare_assemblies.py script, but I'm having issues running pip install edlib.
(mappy was installed without issue)

ERROR: Failed building wheel for edlib
ERROR: Could not build wheels for edlib, which is required to install pyproject.toml-based projects

Thanks so much for any advice!

**Comment by rwilton1** [comment]
Hello again!  I fixed my problem by installing edlib in a conda environment that was created with an older version of python (I used 3.8).  Now compare_assemblies runs perfectly!  It is so useful!

Thanks for all the great tools, tips and tutorials!!!!!

**Comment by rrwick** [comment]
I too am frustrated by edlib not working on recent versions of Python! I've added a note to the [wiki page for this script](https://github.com/rrwick/Perfect-bacterial-genome-tutorial/wiki/Comparing-assemblies) that explains the Python version requirements. Thanks!

**Comment by rwilton1** [comment]
Thanks Ryan!  And I really can’t thank you enough for all the great software and information that you have posted about sequencing (especially Nanopore sequencing) that has really moved the field forward.  And I appreciate your all your detailed notes about installations and linux commands and running software.  From a formerly non-linux/python user, this has really opened up my world (edlib case in point - I can now *sometimes* actually fix things that don’t work😊).

Have a great day!
Rose
