### ISSUE TITLE
ale_score.sh error - tmp file "doesn't look like a PPM file"

### ISSUE THREAD

**Issue by Dwrgi** [rrwick/Perfect-bacterial-genome-tutorial#3]
Hi,
I've tried to generate an ale score for my assembly using the ale_score.sh script, but I get this error message and I can't figure out what's going wrong and where:

**Error message:**
> [main] CMD: bwa mem -t 4 /tmp/tmp.CgDerxPFDu filtered_reads/Pol_01_illumina_1.fastq.gz filtered_reads/Pol_01_illumina_2.fastq.gz
> [main] Real time: 88.395 sec; CPU: 336.350 sec
> Output file will be '/tmp/tmp.QPXOcKrq0l'.                                                         
>  | Loading Image (caching)                                                                         
> 
> *** '/tmp/tmp.BB5XLQvG32' doesn't look like a PPM file.
> 
> *** (To handle other file types, use a version of ALE with
> *** ImageMagick support enabled.)

I've got ALE version 0.9.0.3 as the most up to date I can get via conda.

**Command and full output:**
> $ bash ale_score.sh trycycler_medaka_polypolish_polca.fasta filtered_reads/Pol_01_illumina_1.fastq.gz filtered_reads/Pol_01_illumina_2.fastq.gz 4
> [bwa_index] Pack FASTA... 0.07 sec
> [bwa_index] Construct BWT for the packed sequence...
> [bwa_index] 2.29 seconds elapse.
> [bwa_index] Update BWT... 0.09 sec
> [bwa_index] Pack forward-only FASTA... 0.04 sec
> [bwa_index] Construct SA from BWT and Occ... 0.53 sec
> [main] Version: 0.7.17-r1188
> [main] CMD: bwa index -p /tmp/tmp.CgDerxPFDu trycycler_medaka_polypolish_polca.fasta
> [main] Real time: 3.099 sec; CPU: 3.022 sec
> [M::bwa_idx_load_from_disk] read 0 ALT contigs
> [M::process] read 176862 sequences (40000391 bp)...
> [M::process] read 178286 sequences (40000004 bp)...
> [M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (40, 84881, 2, 35)
> [M::mem_pestat] analyzing insert size distribution for orientation FF...
> [M::mem_pestat] (25, 50, 75) percentile: (506, 591, 753)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (12, 1247)
> [M::mem_pestat] mean and std.dev: (571.33, 176.03)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1494)
> [M::mem_pestat] analyzing insert size distribution for orientation FR...
> [M::mem_pestat] (25, 50, 75) percentile: (624, 722, 840)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (192, 1272)
> [M::mem_pestat] mean and std.dev: (738.03, 162.57)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1488)
> [M::mem_pestat] skip orientation RF as there are not enough pairs
> [M::mem_pestat] analyzing insert size distribution for orientation RR...
> [M::mem_pestat] (25, 50, 75) percentile: (493, 570, 800)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1414)
> [M::mem_pestat] mean and std.dev: (587.12, 222.09)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1721)
> [M::mem_pestat] skip orientation FF
> [M::mem_pestat] skip orientation RR
> [M::mem_process_seqs] Processed 176862 reads in 39.133 CPU sec, 10.776 real sec
> [M::process] read 174134 sequences (40000054 bp)...
> [M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (25, 85500, 0, 34)
> [M::mem_pestat] analyzing insert size distribution for orientation FF...
> [M::mem_pestat] (25, 50, 75) percentile: (401, 601, 761)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1481)
> [M::mem_pestat] mean and std.dev: (584.83, 254.54)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1841)
> [M::mem_pestat] analyzing insert size distribution for orientation FR...
> [M::mem_pestat] (25, 50, 75) percentile: (612, 707, 818)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (200, 1230)
> [M::mem_pestat] mean and std.dev: (720.58, 155.29)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1436)
> [M::mem_pestat] skip orientation RF as there are not enough pairs
> [M::mem_pestat] analyzing insert size distribution for orientation RR...
> [M::mem_pestat] (25, 50, 75) percentile: (541, 614, 745)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (133, 1153)
> [M::mem_pestat] mean and std.dev: (577.10, 162.33)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1357)
> [M::mem_pestat] skip orientation FF
> [M::mem_pestat] skip orientation RR
> [M::mem_process_seqs] Processed 178286 reads in 37.448 CPU sec, 9.515 real sec
> [M::process] read 176118 sequences (40000172 bp)...
> [M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (45, 83635, 1, 30)
> [M::mem_pestat] analyzing insert size distribution for orientation FF...
> [M::mem_pestat] (25, 50, 75) percentile: (504, 625, 792)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1368)
> [M::mem_pestat] mean and std.dev: (621.63, 222.08)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1656)
> [M::mem_pestat] analyzing insert size distribution for orientation FR...
> [M::mem_pestat] (25, 50, 75) percentile: (641, 747, 879)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (165, 1355)
> [M::mem_pestat] mean and std.dev: (767.72, 179.42)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1593)
> [M::mem_pestat] skip orientation RF as there are not enough pairs
> [M::mem_pestat] analyzing insert size distribution for orientation RR...
> [M::mem_pestat] (25, 50, 75) percentile: (515, 656, 832)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1466)
> [M::mem_pestat] mean and std.dev: (631.14, 209.05)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1783)
> [M::mem_pestat] skip orientation FF
> [M::mem_pestat] skip orientation RR
> [M::mem_process_seqs] Processed 174134 reads in 39.470 CPU sec, 10.042 real sec
> [M::process] read 176224 sequences (40000290 bp)...
> [M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (49, 84521, 0, 31)
> [M::mem_pestat] analyzing insert size distribution for orientation FF...
> [M::mem_pestat] (25, 50, 75) percentile: (457, 552, 663)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (45, 1075)
> [M::mem_pestat] mean and std.dev: (524.67, 183.77)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1281)
> [M::mem_pestat] analyzing insert size distribution for orientation FR...
> [M::mem_pestat] (25, 50, 75) percentile: (625, 723, 846)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (183, 1288)
> [M::mem_pestat] mean and std.dev: (741.70, 166.53)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1509)
> [M::mem_pestat] skip orientation RF as there are not enough pairs
> [M::mem_pestat] analyzing insert size distribution for orientation RR...
> [M::mem_pestat] (25, 50, 75) percentile: (594, 706, 879)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (24, 1449)
> [M::mem_pestat] mean and std.dev: (750.83, 226.62)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1734)
> [M::mem_pestat] skip orientation FF
> [M::mem_pestat] skip orientation RR
> [M::mem_process_seqs] Processed 176118 reads in 41.137 CPU sec, 10.416 real sec
> [M::process] read 180900 sequences (40000090 bp)...
> [M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (34, 84623, 1, 46)
> [M::mem_pestat] analyzing insert size distribution for orientation FF...
> [M::mem_pestat] (25, 50, 75) percentile: (493, 627, 841)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1537)
> [M::mem_pestat] mean and std.dev: (657.34, 285.27)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1885)
> [M::mem_pestat] analyzing insert size distribution for orientation FR...
> [M::mem_pestat] (25, 50, 75) percentile: (620, 717, 835)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (190, 1265)
> [M::mem_pestat] mean and std.dev: (733.27, 162.55)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1480)
> [M::mem_pestat] skip orientation RF as there are not enough pairs
> [M::mem_pestat] analyzing insert size distribution for orientation RR...
> [M::mem_pestat] (25, 50, 75) percentile: (490, 573, 681)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (108, 1063)
> [M::mem_pestat] mean and std.dev: (566.50, 150.27)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1254)
> [M::mem_pestat] skip orientation FF
> [M::mem_pestat] skip orientation RR
> [M::mem_process_seqs] Processed 176224 reads in 42.410 CPU sec, 10.729 real sec
> [M::process] read 176218 sequences (40000135 bp)...
> [M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (31, 86626, 0, 43)
> [M::mem_pestat] analyzing insert size distribution for orientation FF...
> [M::mem_pestat] (25, 50, 75) percentile: (469, 578, 662)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (83, 1048)
> [M::mem_pestat] mean and std.dev: (553.00, 150.07)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1241)
> [M::mem_pestat] analyzing insert size distribution for orientation FR...
> [M::mem_pestat] (25, 50, 75) percentile: (590, 677, 775)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (220, 1145)
> [M::mem_pestat] mean and std.dev: (687.70, 139.87)
> [M::mem_pestat] low and high boundaries for proper pairs: (35, 1330)
> [M::mem_pestat] skip orientation RF as there are not enough pairs
> [M::mem_pestat] analyzing insert size distribution for orientation RR...
> [M::mem_pestat] (25, 50, 75) percentile: (429, 521, 647)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1083)
> [M::mem_pestat] mean and std.dev: (523.48, 190.70)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1301)
> [M::mem_pestat] skip orientation FF
> [M::mem_pestat] skip orientation RR
> [M::mem_process_seqs] Processed 180900 reads in 39.740 CPU sec, 10.198 real sec
> [M::process] read 178148 sequences (40000234 bp)...
> [M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (32, 84408, 1, 37)
> [M::mem_pestat] analyzing insert size distribution for orientation FF...
> [M::mem_pestat] (25, 50, 75) percentile: (542, 643, 871)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1529)
> [M::mem_pestat] mean and std.dev: (597.45, 227.31)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1858)
> [M::mem_pestat] analyzing insert size distribution for orientation FR...
> [M::mem_pestat] (25, 50, 75) percentile: (611, 705, 815)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (203, 1223)
> [M::mem_pestat] mean and std.dev: (718.85, 154.51)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1427)
> [M::mem_pestat] skip orientation RF as there are not enough pairs
> [M::mem_pestat] analyzing insert size distribution for orientation RR...
> [M::mem_pestat] (25, 50, 75) percentile: (441, 536, 669)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1125)
> [M::mem_pestat] mean and std.dev: (532.14, 149.13)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1353)
> [M::mem_pestat] skip orientation FF
> [M::mem_pestat] skip orientation RR
> [M::mem_process_seqs] Processed 176218 reads in 39.621 CPU sec, 10.075 real sec
> [M::process] read 70084 sequences (15970297 bp)...
> [M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (36, 85400, 0, 26)
> [M::mem_pestat] analyzing insert size distribution for orientation FF...
> [M::mem_pestat] (25, 50, 75) percentile: (454, 535, 712)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1228)
> [M::mem_pestat] mean and std.dev: (576.29, 170.59)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1486)
> [M::mem_pestat] analyzing insert size distribution for orientation FR...
> [M::mem_pestat] (25, 50, 75) percentile: (606, 700, 808)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (202, 1212)
> [M::mem_pestat] mean and std.dev: (713.48, 152.93)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1414)
> [M::mem_pestat] skip orientation RF as there are not enough pairs
> [M::mem_pestat] analyzing insert size distribution for orientation RR...
> [M::mem_pestat] (25, 50, 75) percentile: (444, 575, 684)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1164)
> [M::mem_pestat] mean and std.dev: (573.40, 181.24)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1404)
> [M::mem_pestat] skip orientation FF
> [M::mem_pestat] skip orientation RR
> [M::mem_process_seqs] Processed 178148 reads in 39.447 CPU sec, 10.011 real sec
> [M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (12, 33640, 0, 14)
> [M::mem_pestat] analyzing insert size distribution for orientation FF...
> [M::mem_pestat] (25, 50, 75) percentile: (585, 711, 838)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (79, 1344)
> [M::mem_pestat] mean and std.dev: (716.17, 243.83)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1691)
> [M::mem_pestat] analyzing insert size distribution for orientation FR...
> [M::mem_pestat] (25, 50, 75) percentile: (622, 719, 834)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (198, 1258)
> [M::mem_pestat] mean and std.dev: (734.26, 161.02)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1470)
> [M::mem_pestat] skip orientation RF as there are not enough pairs
> [M::mem_pestat] analyzing insert size distribution for orientation RR...
> [M::mem_pestat] (25, 50, 75) percentile: (483, 567, 741)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1257)
> [M::mem_pestat] mean and std.dev: (575.46, 124.30)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1515)
> [M::mem_pestat] skip orientation FF
> [M::mem_pestat] skip orientation RR
> [M::mem_process_seqs] Processed 70084 reads in 16.092 CPU sec, 4.086 real sec
> [main] Version: 0.7.17-r1188
> [main] CMD: bwa mem -t 4 /tmp/tmp.CgDerxPFDu filtered_reads/Pol_01_illumina_1.fastq.gz filtered_reads/Pol_01_illumina_2.fastq.gz
> [main] Real time: 88.395 sec; CPU: 336.350 sec
> Output file will be '/tmp/tmp.QPXOcKrq0l'.                                                         
>  | Loading Image (caching)                                                                         
> 
> *** '/tmp/tmp.BB5XLQvG32' doesn't look like a PPM file.
> 
> *** (To handle other file types, use a version of ALE with
> *** ImageMagick support enabled.)

**Comment by rrwick** [comment]
Based on that version number, I suspect you've got the wrong ALE tool installed. There are a few tools named 'ALE', but the one you want is this one: https://github.com/sc932/ALE. The correct ALE is in bioconda, but the ALE in conda-forge is something else. ALE is also pretty easy to build from source (just clone it and run `make`) so you can skip conda altogether if that makes things easier.

Hope that helps!

**Comment by Dwrgi** [comment]
Hi, Thanks! I've chucked out the ale that was there and installed the correct one from github, but I still get an image/PPM related error:

> bash ale_score.sh Pol_01_trycycler_medaka_polypolish_polca.fasta filtered_reads/Pol_01_illumina_1.fastq.gz filtered_reads/Pol_01_illumina_2.fastq.gz 4
> [bwa_index] Pack FASTA... 0.08 sec
> [bwa_index] Construct BWT for the packed sequence...
> [bwa_index] 2.10 seconds elapse.
> [bwa_index] Update BWT... 0.09 sec
> [bwa_index] Pack forward-only FASTA... 0.04 sec
> [bwa_index] Construct SA from BWT and Occ... 0.70 sec
> [main] Version: 0.7.17-r1188
> [main] CMD: bwa index -p /tmp/tmp.xD5Xz1l7Sg Pol_01_trycycler_medaka_polypolish_polca.fasta
> [main] Real time: 3.109 sec; CPU: 3.021 sec
> [M::bwa_idx_load_from_disk] read 0 ALT contigs
> [M::process] read 176862 sequences (40000391 bp)...
> [M::process] read 178286 sequences (40000004 bp)...
> [M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (40, 84881, 2, 35)
> [M::mem_pestat] analyzing insert size distribution for orientation FF...
> [M::mem_pestat] (25, 50, 75) percentile: (506, 591, 753)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (12, 1247)
> [M::mem_pestat] mean and std.dev: (571.33, 176.03)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1494)
> [M::mem_pestat] analyzing insert size distribution for orientation FR...
> [M::mem_pestat] (25, 50, 75) percentile: (624, 722, 840)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (192, 1272)
> [M::mem_pestat] mean and std.dev: (738.03, 162.57)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1488)
> [M::mem_pestat] skip orientation RF as there are not enough pairs
> [M::mem_pestat] analyzing insert size distribution for orientation RR...
> [M::mem_pestat] (25, 50, 75) percentile: (493, 570, 800)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1414)
> [M::mem_pestat] mean and std.dev: (587.12, 222.09)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1721)
> [M::mem_pestat] skip orientation FF
> [M::mem_pestat] skip orientation RR
> [M::mem_process_seqs] Processed 176862 reads in 36.719 CPU sec, 9.351 real sec
> [M::process] read 174134 sequences (40000054 bp)...
> [M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (25, 85500, 0, 34)
> [M::mem_pestat] analyzing insert size distribution for orientation FF...
> [M::mem_pestat] (25, 50, 75) percentile: (401, 601, 761)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1481)
> [M::mem_pestat] mean and std.dev: (584.83, 254.54)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1841)
> [M::mem_pestat] analyzing insert size distribution for orientation FR...
> [M::mem_pestat] (25, 50, 75) percentile: (612, 707, 818)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (200, 1230)
> [M::mem_pestat] mean and std.dev: (720.58, 155.29)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1436)
> [M::mem_pestat] skip orientation RF as there are not enough pairs
> [M::mem_pestat] analyzing insert size distribution for orientation RR...
> [M::mem_pestat] (25, 50, 75) percentile: (541, 614, 745)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (133, 1153)
> [M::mem_pestat] mean and std.dev: (577.10, 162.33)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1357)
> [M::mem_pestat] skip orientation FF
> [M::mem_pestat] skip orientation RR
> [M::mem_process_seqs] Processed 178286 reads in 37.160 CPU sec, 9.622 real sec
> [M::process] read 176118 sequences (40000172 bp)...
> [M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (45, 83635, 1, 30)
> [M::mem_pestat] analyzing insert size distribution for orientation FF...
> [M::mem_pestat] (25, 50, 75) percentile: (504, 625, 792)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1368)
> [M::mem_pestat] mean and std.dev: (621.63, 222.08)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1656)
> [M::mem_pestat] analyzing insert size distribution for orientation FR...
> [M::mem_pestat] (25, 50, 75) percentile: (641, 747, 879)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (165, 1355)
> [M::mem_pestat] mean and std.dev: (767.72, 179.42)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1593)
> [M::mem_pestat] skip orientation RF as there are not enough pairs
> [M::mem_pestat] analyzing insert size distribution for orientation RR...
> [M::mem_pestat] (25, 50, 75) percentile: (515, 656, 832)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1466)
> [M::mem_pestat] mean and std.dev: (631.14, 209.05)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1783)
> [M::mem_pestat] skip orientation FF
> 
> [M::mem_pestat] skip orientation RR
> 
> [M::mem_process_seqs] Processed 174134 reads in 36.342 CPU sec, 9.517 real sec
> 
> [M::process] read 176224 sequences (40000290 bp)...
> 
> [M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (49, 84521, 0, 31)
> 
> [M::mem_pestat] analyzing insert size distribution for orientation FF...
> 
> [M::mem_pestat] (25, 50, 75) percentile: (457, 552, 663)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (45, 1075)
> [M::mem_pestat] mean and std.dev: (524.67, 183.77)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1281)
> [M::mem_pestat] analyzing insert size distribution for orientation FR...
> [M::mem_pestat] (25, 50, 75) percentile: (625, 723, 846)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (183, 1288)
> [M::mem_pestat] mean and std.dev: (741.70, 166.53)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1509)
> [M::mem_pestat] skip orientation RF as there are not enough pairs
> [M::mem_pestat] analyzing insert size distribution for orientation RR...
> [M::mem_pestat] (25, 50, 75) percentile: (594, 706, 879)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (24, 1449)
> 
> [M::mem_pestat] mean and std.dev: (750.83, 226.62)
> 
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1734)
> 
> [M::mem_pestat] skip orientation FF
> 
> [M::mem_pestat] skip orientation RR
> 
> [M::mem_process_seqs] Processed 176118 reads in 37.129 CPU sec, 9.470 real sec
> [M::process] read 180900 sequences (40000090 bp)...
> [M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (34, 84623, 1, 46)
> [M::mem_pestat] analyzing insert size distribution for orientation FF...
> [M::mem_pestat] (25, 50, 75) percentile: (493, 627, 841)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1537)
> [M::mem_pestat] mean and std.dev: (657.34, 285.27)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1885)
> [M::mem_pestat] analyzing insert size distribution for orientation FR...
> [M::mem_pestat] (25, 50, 75) percentile: (620, 717, 835)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (190, 1265)
> [M::mem_pestat] mean and std.dev: (733.27, 162.55)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1480)
> [M::mem_pestat] skip orientation RF as there are not enough pairs
> [M::mem_pestat] analyzing insert size distribution for orientation RR...
> [M::mem_pestat] (25, 50, 75) percentile: (490, 573, 681)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (108, 1063)
> [M::mem_pestat] mean and std.dev: (566.50, 150.27)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1254)
> [M::mem_pestat] skip orientation FF
> [M::mem_pestat] skip orientation RR
> [M::mem_process_seqs] Processed 176224 reads in 37.580 CPU sec, 9.506 real sec
> [M::process] read 176218 sequences (40000135 bp)...
> [M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (31, 86626, 0, 43)
> [M::mem_pestat] analyzing insert size distribution for orientation FF...
> [M::mem_pestat] (25, 50, 75) percentile: (469, 578, 662)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (83, 1048)
> [M::mem_pestat] mean and std.dev: (553.00, 150.07)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1241)
> [M::mem_pestat] analyzing insert size distribution for orientation FR...
> [M::mem_pestat] (25, 50, 75) percentile: (590, 677, 775)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (220, 1145)
> [M::mem_pestat] mean and std.dev: (687.70, 139.87)
> [M::mem_pestat] low and high boundaries for proper pairs: (35, 1330)
> [M::mem_pestat] skip orientation RF as there are not enough pairs
> [M::mem_pestat] analyzing insert size distribution for orientation RR...
> [M::mem_pestat] (25, 50, 75) percentile: (429, 521, 647)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1083)
> [M::mem_pestat] mean and std.dev: (523.48, 190.70)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1301)
> [M::mem_pestat] skip orientation FF
> [M::mem_pestat] skip orientation RR
> [M::mem_process_seqs] Processed 180900 reads in 40.264 CPU sec, 10.208 real sec
> [M::process] read 178148 sequences (40000234 bp)...
> [M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (32, 84408, 1, 37)
> [M::mem_pestat] analyzing insert size distribution for orientation FF...
> [M::mem_pestat] (25, 50, 75) percentile: (542, 643, 871)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1529)
> [M::mem_pestat] mean and std.dev: (597.45, 227.31)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1858)
> [M::mem_pestat] analyzing insert size distribution for orientation FR...
> [M::mem_pestat] (25, 50, 75) percentile: (611, 705, 815)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (203, 1223)
> [M::mem_pestat] mean and std.dev: (718.85, 154.51)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1427)
> [M::mem_pestat] skip orientation RF as there are not enough pairs
> [M::mem_pestat] analyzing insert size distribution for orientation RR...
> [M::mem_pestat] (25, 50, 75) percentile: (441, 536, 669)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1125)
> [M::mem_pestat] mean and std.dev: (532.14, 149.13)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1353)
> [M::mem_pestat] skip orientation FF
> [M::mem_pestat] skip orientation RR
> [M::mem_process_seqs] Processed 176218 reads in 37.520 CPU sec, 9.717 real sec
> [M::process] read 70084 sequences (15970297 bp)...
> [M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (36, 85400, 0, 26)
> [M::mem_pestat] analyzing insert size distribution for orientation FF...
> [M::mem_pestat] (25, 50, 75) percentile: (454, 535, 712)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1228)
> [M::mem_pestat] mean and std.dev: (576.29, 170.59)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1486)
> [M::mem_pestat] analyzing insert size distribution for orientation FR...
> [M::mem_pestat] (25, 50, 75) percentile: (606, 700, 808)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (202, 1212)
> [M::mem_pestat] mean and std.dev: (713.48, 152.93)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1414)
> [M::mem_pestat] skip orientation RF as there are not enough pairs
> [M::mem_pestat] analyzing insert size distribution for orientation RR...
> [M::mem_pestat] (25, 50, 75) percentile: (444, 575, 684)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1164)
> [M::mem_pestat] mean and std.dev: (573.40, 181.24)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1404)
> [M::mem_pestat] skip orientation FF
> [M::mem_pestat] skip orientation RR
> [M::mem_process_seqs] Processed 178148 reads in 36.387 CPU sec, 9.223 real sec
> [M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (12, 33640, 0, 14)
> [M::mem_pestat] analyzing insert size distribution for orientation FF...
> [M::mem_pestat] (25, 50, 75) percentile: (585, 711, 838)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (79, 1344)
> [M::mem_pestat] mean and std.dev: (716.17, 243.83)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1691)
> [M::mem_pestat] analyzing insert size distribution for orientation FR...
> [M::mem_pestat] (25, 50, 75) percentile: (622, 719, 834)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (198, 1258)
> [M::mem_pestat] mean and std.dev: (734.26, 161.02)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1470)
> [M::mem_pestat] skip orientation RF as there are not enough pairs
> [M::mem_pestat] analyzing insert size distribution for orientation RR...
> [M::mem_pestat] (25, 50, 75) percentile: (483, 567, 741)
> [M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1257)
> [M::mem_pestat] mean and std.dev: (575.46, 124.30)
> [M::mem_pestat] low and high boundaries for proper pairs: (1, 1515)
> [M::mem_pestat] skip orientation FF
> [M::mem_pestat] skip orientation RR
> [M::mem_process_seqs] Processed 70084 reads in 13.951 CPU sec, 3.547 real sec
> [main] Version: 0.7.17-r1188
> [main] CMD: bwa mem -t 4 /tmp/tmp.xD5Xz1l7Sg filtered_reads/Pol_01_illumina_1.fastq.gz filtered_reads/Pol_01_illumina_2.fastq.gz
> [main] Real time: 82.574 sec; CPU: 314.927 sec
> Output file will be '/tmp/tmp.YtrOWZUnlp'.                                                            
>  | Loading Image (caching)                                                                            

> *** '/tmp/tmp.EgnoFiruIa' doesn't look like a PPM file.

> *** (To handle other file types, use a version of ALE with
> *** ImageMagick support enabled.)




> ALE -h
> Welcome to the Assembly Likelihood Estimator!
> (C) 2010 Scott Clark
> 
> Usage: ALE [-options] alignments.[s|b]am assembly.fasta[.gz] ALEoutput.txt
> 
> Options: <i>nt <f>loat <s>tring [default]
> -h or --help    : print out this help
> --kmer <f>      : Kmer depth for kmer stats [4]
> --qOff <i>      : Quality ascii offset (illumina) [33] or 64 (or 0)
> --pl <s>        : placementOutputBAM
> --pm <s>        : library parameter file (auto outputs .param)
> --nout          : only output meta information (no per base) [off]
> --minLL         : the minimum log Likelihood (-120)
> --metagenome    : Evaluate each contig independently for depth & kmer metrics
> --realign[=matchScore,misMatchPenalty,gapOpenPenalty,gapExtPenalty,minimumSoftClip (default: 1,3,11,4,8) ]
>                    Realign reads with Striped-Smith-Waterman honoring ambiguous reference bases
>                    and stacking homo-polymer indels
>                    for PacBio, try --realign=1,5,2,1,20 (similar to BWA-SW recommendations)
> --SNPreport <s> : Creates a new text file reporting all SNP phasing 
>                    observed by a read against ambiguous bases in the reference
> --minQual <i>   : Minimum quality score to use in Z-normalization (default 3).
>                    Illumina quality scores can be unreliable below this threshold

**Comment by rrwick** [comment]
That error message (`use a version of ALE with ImageMagick support enabled`) suggests to me that you have a different `ALE` installed: Anti-Lamenessing Engine (I know nothing about it - just found in a Google search). But you also clearly have the correct `ALE` installed, based on the help output.

So I think the issue might be with your environment, PATH variable or something like that. Maybe try to find all executables you have named `ALE` and uninstall the image-processing one?

**Comment by Dwrgi** [comment]
Thanks! Now that I knew what I was looking for I managed to find it (only the 'wrong' ale (ale 0.9.0.3-5) showed up in the list of installed packages) and get rid of it, so everything is working fine. :)

**Comment by rrwick** [comment]
Great - glad to hear it!
