### ISSUE TITLE
Checking differences in IGV - 

### ISSUE THREAD

**Issue by Dwrgi** [rrwick/Perfect-bacterial-genome-tutorial#4]
Hi,
When following the instructions in [Checking differences in IGV Step 2](https://github.com/rrwick/Perfect-bacterial-genome-tutorial/wiki/Checking-differences-in-IGV#step-2-align-short-and-long-reads) (but with -t 4), I get the following error message: 

> [bam_header_read] EOF marker is absent. The input is probably truncated.
> [bam_header_read] invalid BAM binary header (this is not a BAM file).
> [bam_index_core] Invalid BAM header.[bam_index_build2] fail to index the BAM file.
> [bam_header_read] EOF marker is absent. The input is probably truncated.
> [bam_header_read] invalid BAM binary header (this is not a BAM file).
> [bam_index_core] Invalid BAM header.[bam_index_build2] fail to index the BAM file.

I don't quite know where to start with this one?

The only other thing that does seem to hint at the issue is this comment in the output:

> Usage:   samtools sort [options] <in.bam> <out.prefix>
> 
> Options: -n        sort by read name
>          -f        use <out.prefix> as full file name instead of prefix
>          -o        final output to stdout
>          -l INT    compression level, from 0 to 9 [-1]
>          -@ INT    number of sorting and compression threads [1]
>          -m INT    max memory per thread; suffix K/M/G recognized [768M]

**Comment by rrwick** [comment]
I'm not sure, but I suspect the issue may be with your version of samtools. Older versions of samtools (e.g. v0.1.19) have a different usage than newer versions (e.g. v1.16.1).

If this is the problem, I'd recommend upgrading your samtools. If that's not possible, you can probably make the older version work, but I think you might have to explicitly tell it to read from stdin and output to stdout, so perhaps something like this:
```bash
bwa mem -t 4 before.fasta "$illumina_1" "$illumina_2" | samtools sort - - > before_short.bam
```
Note - I'm not certain about that command - you might have to dig up some old documentation!

Ryan

**Comment by Dwrgi** [comment]
I think the problem might have been that I was still in the conda environment. I double-checked everything was as up-to-date as I could get it and then tried again and it was working fine. Now to the hard part of making sense of it all ! :)

Thank you for your help!
