### ISSUE TITLE
Rounds of polishing

### ISSUE THREAD

**Issue by erinyoung** [rrwick/Perfect-bacterial-genome-tutorial#5]
I have read through the paper and tutorials (which are fantastic by the way), and it appears that the "easy" tutorial has one round of polypolish followed by one round of polca. Is this a correct assumption? Or is there an intention to repeat polishing steps for either or both of these tools?

**Comment by rrwick** [comment]
Hi Erin,

You're right, I only included one round of each tool in the tutorial. Assuming your input genome is in pretty good shape, subsequent polishing rounds with Polypolish or POLCA probably won't make any changes. When I benchmarked various polishers, the only one which noticeably benefitted from multiple rounds was Pilon (see Figure S4 in the [Polypolish paper](https://doi.org/10.1371/journal.pcbi.1009802)). But no harm in trying! And if there do happen to be any second-round polishing changes, then they are probably worth investigating (e.g. with [IGV](https://github.com/rrwick/Perfect-bacterial-genome-tutorial/wiki/Checking-differences-in-IGV)).

Ryan
