### ISSUE TITLE
list index out of range error in comapre_assemblies.py

### ISSUE THREAD

**Issue by Gr1m3y** [rrwick/Perfect-bacterial-genome-tutorial#6]
I was running through your tutorial (really great work by the way!) and ran into some issues with the compare_assemblies.py script. I want to compare my assembly to a reference assembly of a different length. When I run the script, it performs the alignment, shows the first differing block, but then I get an error.

```
Traceback (most recent call last):
  File "../scripts/compare_assemblies.py", line 575, in <module>
    main()
  File "../scripts/compare_assemblies.py", line 41, in main
    align_sequences(assembly_1, assembly_2, args.padding, args.merge, args.aligner)
  File "../scripts/compare_assemblies.py", line 140, in align_sequences
    output_differences(assembly_1_name, assembly_1_seq, assembly_2_name, assembly_2_seq, padding, merge,
  File "../scripts/compare_assemblies.py", line 168, in output_differences
    assembly_1_start, assembly_1_end = assembly_1_pos[start], assembly_1_pos[end]
IndexError: list index out of range
```

I have looked briefly at the code, but I am not entirely sure where the issue is occurring. If I find anything, I will let you know, but thought I would report it so that you have it on your radar.

**Comment by rrwick** [comment]
I finally encountered this bug myself - it seems to occur when two sequences differ at their final base, e.g. `ACG` vs `ACGT`. I believe it's fixed now: 8acbfb2

Thanks!
