### ISSUE TITLE
Cannot Install Trycycler

### ISSUE THREAD

**Issue by Dabiguina94** [rrwick/Perfect-bacterial-genome-tutorial#7]
Hi! I've been using the following command line for trycycler installation in conda:

conda install -c bioconda -c conda-forge trycycler

but allways I cannot installing it, I've tryied in a Linux computer and now in a Macbook, both have Python >3.9
instead, I have this

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 

It can stay there for hours

**Comment by MostafaYA** [comment]
Try with mamba 
`mamba  create -n trycycler -c bioconda trycycler`
