### ISSUE TITLE
Error with mash when trying to cluster contigs

### ISSUE THREAD

**Issue by benn888** [rrwick/Perfect-bacterial-genome-tutorial#8]
Hi everyone!
First of all, many thanks for the amazing work!

I created the assembly environment using the conda environment file and I'm now following the tutorial.

I'm facing an issue when trying to cluster contigs with the following command: 

`trycycler cluster --assemblies assemblies/*.fasta --reads reads_qc/ont.fastq --out_dir trycycler`

I'm getting this error message: 

"_Checking required software: Error: unable to determine Mash version - make sure that Mash is correctly installed, then try again._"

Weird since mash is in my path...

I also ran this command:

`mash --help`

and got this message:

"_mash: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory_"

Can anyone help on this?

Thank you in advance!

**Comment by rrwick** [comment]
Sounds like something has gone wrong with your Mash installation :confused:

For what it's worth, their pre-build binaries (https://github.com/marbl/Mash/releases) have always worked well for me! Or else you could try installing Mash with a package manager, e.g. apt or homebrew.
