### ISSUE TITLE
miniasm_and_minipolish step didn't run without intervention

### ISSUE THREAD

**Issue by jaimiewest** [rrwick/Perfect-bacterial-genome-tutorial#9]
I needed to manually put the miniasm_and_minipolish.sh in my working folder and modify the tutorial code in order to get the function to run. Is there a more elegant solution?

Also had to add any2fasta to the environment.yml.

**Comment by rrwick** [comment]
You can put `miniasm_and_minipolish.sh` in a directory that's in your `PATH` variable, and if you want to keep it specific to your conda environment, that might be something like  `~/miniconda3/envs/assembly/bin`. To check this directory, try running `which` on something else in your conda environment. Also, make sure the file has executable permissions set. Then you should be able to run it from any directory using just `miniasm_and_minipolish.sh`.

And thanks for pointing out that `any2fasta` was missing from the conda environment file - I've just added it!

**Comment by jaimiewest** [comment]
that is extremely helpful!
